### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by woodoo46** [EichlerLab/svpop#2]
Hi there,

It might have been mentioned somewhere, I may have missed it. I am wondering if there is an example on how to use this software, eg where to define the inputs?

Thanks.

George

**Comment by paudano** [comment]
It's currently not well documented and used by other tools, such as PAV (https://github.com/EichlerLab/pav). There was a major change to the structure of the pipeline, and the documentation needs to be updated (better file structure, uses gzipped files whenever possible). I'll be working on this next (just pushed a major PAV update).

In short, you run Snakemake and request the desired output file. There's no defined end-point for the pipeline, you ask it for the data, merges, or annotations you need using a set file-structure. Currently, it takes going into the Snakemake rules to find the annotations you want. This will never be a fully mature pipeline, it's a collection of things I find useful in my own work. However, I'll do my best to document it so that others can find something useful in it.

I'll update this ticket once I update the README and push it.

**Comment by paudano** [comment]
Documentation updated.
